### PR TITLE
Limited compile process for smaller machine

### PR DESCRIPTION
**Pull request by walloutlet**
Added a compile process limit statement, as I was having significant issues trying to compile this code and ESPHome crashing.  Hopefully, this helps other people more easily compile this code in ESPHome.

### CODE REVIEW

**Comment by formatBCE** [comment]
Interesting! I have no troubles at all, and this isn't added to NabuCasa PE YAML.
Does it slow down the build?

**Comment by walloutlet** [comment]
Not at all... build time is reasonable, considering that I was never successful at compiling this code to the end.  ESPHome would simply crash.  I tried using fresh installs of ESPHome on Docker Desktop, Docker on Ubuntu, manual install of ESPHome on Ubuntu and nothing would compile.  No errors on compile, ESPHome would simply crash, assuming memory or some sort of resource constraint but I can't for the life of me figure out what would be crashing.  Scouring the Internet I ran across this post (https://community.home-assistant.io/t/compilation-fails-xtensa-lx106-elf-g-fatal-error-killed-signal-terminated-program-cc1plus/463184/18) and this did the trick.

**Comment by formatBCE** [comment]
Ok, i read about that option. It's intended to limit the compiler processes to 1 on weak hardware, like RPi3. 
Case is, that this option will significantly slow down the build process for decent hardware, and should be used only if it fails without it.
I will leave YAML as-is. If person runs ESPHome on weak hardware, they probably already know the problem and will add it locally - and I don't want restrain others with this option.
Voice satellites hardware is pretty demanding, so its build process requires big amount of processing power.

**Comment by walloutlet** [comment]
No worries... worst case this PR comes up in someone's search and helps them out.

**Comment by formatBCE** [comment]
Thank you for understanding!

**Comment by walloutlet** [comment]
Appreciate your time and effort on this, especially getting the high quality audio going.  Once compiled, it works real nice.

**Pull request closed without merging**
